
converter: 'core.SegmentMaskConverter.SegmentMaskConverter'

backup_params:
  input_dir: '../raw'

  image_quality: 100
  task_name: 'testin'

  class_map:
    # object name, object color (also for segm. mask), type of object for cvat annotations.json
    0:
      'name': 'test'
      'color': [255, 255, 255]
      'type': 'polygon'
