
converter: 'converters.YoloV8BboxTxtConverter'

backup_params:
  input_dir: 'test'

  image_quality: 100
  task_name: 'testin'

  class_map:
    # object name, object color (also for segm. mask), type of object in cvat
    0: ['test', [255, 255, 255], 'polygon']

