# WARNING. Never use black with CVAT Segmentation masks beacuse BG in CVAT Segm. mask is black

converter: 'core.YoloV8TxtConverters.YoloV8SegmTxtConverter'

backup_params:
  input_dir: '../input-txt'

  image_quality: 100
  task_name: 'second_stable'

  class_map:
    # object name, object color (also for segm. mask), type of object for cvat annotations.json
    0:
      'name': 'test'
      'color': [255, 255, 255]
      'type': 'polygon'

    1:
      'name': 'green'
      'color': [0, 255, 0]
      'type': polygon
